name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      run: make build
      env:
        BUILDER: default
        ARCHITECTURES: linux/amd64,linux/arm64

    - name: Push
      run: make push
      env:
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        
