name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Buildx
      id: setup-buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build
      run: make build
      env:
        BUILDER: ${{ steps.setup-buildx.outputs.name }}
        ARCHITECTURES: linux/amd64,linux/arm64
        BUILD_ACTION: --load --output="type=image"

    - name: Push
      run: make push
      env:
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        